name: lyon1agenda
description: A package to fetch ics files from ADE Lyon 1
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.15.1 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.20.1
dependencies: 
  dartz: ^0.10.1
  requests: ^4.7.0
  icalendar_parser: ^1.0.1
  dartus: 
   git: https://github.com/hatch01/dartus-tomuss-client.git
  dotenv: ^4.0.1
